# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Time_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='BeaconSignal.proto',
  package='rockin_msgs',
  serialized_pb='\n\x12\x42\x65\x61\x63onSignal.proto\x12\x0brockin_msgs\x1a\nTime.proto\"\x8a\x01\n\x0c\x42\x65\x61\x63onSignal\x12\x1f\n\x04time\x18\x01 \x02(\x0b\x32\x11.rockin_msgs.Time\x12\x0b\n\x03seq\x18\x02 \x02(\x04\x12\x11\n\tteam_name\x18\x03 \x02(\t\x12\x11\n\tpeer_name\x18\x04 \x02(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x01\x42,\n\x16org.rockin.common_msgsB\x12\x42\x65\x61\x63onSignalProtos')



_BEACONSIGNAL_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.BeaconSignal.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=186,
)


_BEACONSIGNAL = descriptor.Descriptor(
  name='BeaconSignal',
  full_name='rockin_msgs.BeaconSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='rockin_msgs.BeaconSignal.time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seq', full_name='rockin_msgs.BeaconSignal.seq', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='team_name', full_name='rockin_msgs.BeaconSignal.team_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='peer_name', full_name='rockin_msgs.BeaconSignal.peer_name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BEACONSIGNAL_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=186,
)

_BEACONSIGNAL.fields_by_name['time'].message_type = Time_pb2._TIME
_BEACONSIGNAL_COMPTYPE.containing_type = _BEACONSIGNAL;
DESCRIPTOR.message_types_by_name['BeaconSignal'] = _BEACONSIGNAL

class BeaconSignal(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BEACONSIGNAL
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.BeaconSignal)

# @@protoc_insertion_point(module_scope)
