# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='CompressedImage.proto',
  package='rockin_msgs',
  serialized_pb='\n\x15\x43ompressedImage.proto\x12\x0brockin_msgs\"X\n\x0f\x43ompressedImage\x12\x0e\n\x06\x66ormat\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xf5\x03\x42/\n\x16org.rockin.common_msgsB\x15\x43ompressedImageProtos')



_COMPRESSEDIMAGE_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.CompressedImage.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=501,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=87,
  serialized_end=126,
)


_COMPRESSEDIMAGE = descriptor.Descriptor(
  name='CompressedImage',
  full_name='rockin_msgs.CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='format', full_name='rockin_msgs.CompressedImage.format', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='rockin_msgs.CompressedImage.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPRESSEDIMAGE_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=126,
)

_COMPRESSEDIMAGE_COMPTYPE.containing_type = _COMPRESSEDIMAGE;
DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE

class CompressedImage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPRESSEDIMAGE
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.CompressedImage)

# @@protoc_insertion_point(module_scope)
