# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ConveyorBelt.proto',
  package='rockin_msgs',
  serialized_pb='\n\x12\x43onveyorBelt.proto\x12\x0brockin_msgs\"n\n\x12\x43onveyorBeltStatus\x12/\n\x05state\x18\x01 \x02(\x0e\x32 .rockin_msgs.ConveyorBeltRunMode\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xac\x02\"q\n\x13\x43onveyorBeltCommand\x12\x31\n\x07\x63ommand\x18\x01 \x02(\x0e\x32 .rockin_msgs.ConveyorBeltRunMode\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xad\x02**\n\x13\x43onveyorBeltRunMode\x12\x08\n\x04STOP\x10\x00\x12\t\n\x05START\x10\x01\x42,\n\x16org.rockin.common_msgsB\x12\x43onveyorBeltProtos')

_CONVEYORBELTRUNMODE = descriptor.EnumDescriptor(
  name='ConveyorBeltRunMode',
  full_name='rockin_msgs.ConveyorBeltRunMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=262,
  serialized_end=304,
)


STOP = 0
START = 1


_CONVEYORBELTSTATUS_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.ConveyorBeltStatus.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=300,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=145,
)

_CONVEYORBELTCOMMAND_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.ConveyorBeltCommand.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=301,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=221,
  serialized_end=260,
)


_CONVEYORBELTSTATUS = descriptor.Descriptor(
  name='ConveyorBeltStatus',
  full_name='rockin_msgs.ConveyorBeltStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='state', full_name='rockin_msgs.ConveyorBeltStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONVEYORBELTSTATUS_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=145,
)


_CONVEYORBELTCOMMAND = descriptor.Descriptor(
  name='ConveyorBeltCommand',
  full_name='rockin_msgs.ConveyorBeltCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='rockin_msgs.ConveyorBeltCommand.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONVEYORBELTCOMMAND_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=147,
  serialized_end=260,
)

_CONVEYORBELTSTATUS.fields_by_name['state'].enum_type = _CONVEYORBELTRUNMODE
_CONVEYORBELTSTATUS_COMPTYPE.containing_type = _CONVEYORBELTSTATUS;
_CONVEYORBELTCOMMAND.fields_by_name['command'].enum_type = _CONVEYORBELTRUNMODE
_CONVEYORBELTCOMMAND_COMPTYPE.containing_type = _CONVEYORBELTCOMMAND;
DESCRIPTOR.message_types_by_name['ConveyorBeltStatus'] = _CONVEYORBELTSTATUS
DESCRIPTOR.message_types_by_name['ConveyorBeltCommand'] = _CONVEYORBELTCOMMAND

class ConveyorBeltStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONVEYORBELTSTATUS
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.ConveyorBeltStatus)

class ConveyorBeltCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONVEYORBELTCOMMAND
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.ConveyorBeltCommand)

# @@protoc_insertion_point(module_scope)
