# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='DrillingMachine.proto',
  package='rockin_msgs',
  serialized_pb='\n\x15\x44rillingMachine.proto\x12\x0brockin_msgs\"\xca\x01\n\x15\x44rillingMachineStatus\x12\x37\n\x05state\x18\x01 \x02(\x0e\x32(.rockin_msgs.DrillingMachineStatus.State\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xae\x02\"O\n\x05State\x12\n\n\x06\x41T_TOP\x10\x00\x12\r\n\tAT_BOTTOM\x10\x01\x12\r\n\tMOVING_UP\x10\x02\x12\x0f\n\x0bMOVING_DOWN\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\"\xa6\x01\n\x16\x44rillingMachineCommand\x12<\n\x07\x63ommand\x18\x01 \x02(\x0e\x32+.rockin_msgs.DrillingMachineCommand.Command\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xaf\x02\"%\n\x07\x43ommand\x12\r\n\tMOVE_DOWN\x10\x00\x12\x0b\n\x07MOVE_UP\x10\x01\x42/\n\x16org.rockin.common_msgsB\x15\x44rillingMachineProtos')



_DRILLINGMACHINESTATUS_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.DrillingMachineStatus.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=302,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=160,
)

_DRILLINGMACHINESTATUS_STATE = descriptor.EnumDescriptor(
  name='State',
  full_name='rockin_msgs.DrillingMachineStatus.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AT_TOP', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AT_BOTTOM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVING_UP', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVING_DOWN', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=162,
  serialized_end=241,
)

_DRILLINGMACHINECOMMAND_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.DrillingMachineCommand.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=303,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=332,
  serialized_end=371,
)

_DRILLINGMACHINECOMMAND_COMMAND = descriptor.EnumDescriptor(
  name='Command',
  full_name='rockin_msgs.DrillingMachineCommand.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MOVE_DOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVE_UP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=373,
  serialized_end=410,
)


_DRILLINGMACHINESTATUS = descriptor.Descriptor(
  name='DrillingMachineStatus',
  full_name='rockin_msgs.DrillingMachineStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='state', full_name='rockin_msgs.DrillingMachineStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRILLINGMACHINESTATUS_COMPTYPE,
    _DRILLINGMACHINESTATUS_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=241,
)


_DRILLINGMACHINECOMMAND = descriptor.Descriptor(
  name='DrillingMachineCommand',
  full_name='rockin_msgs.DrillingMachineCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='rockin_msgs.DrillingMachineCommand.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRILLINGMACHINECOMMAND_COMPTYPE,
    _DRILLINGMACHINECOMMAND_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=244,
  serialized_end=410,
)

_DRILLINGMACHINESTATUS.fields_by_name['state'].enum_type = _DRILLINGMACHINESTATUS_STATE
_DRILLINGMACHINESTATUS_COMPTYPE.containing_type = _DRILLINGMACHINESTATUS;
_DRILLINGMACHINESTATUS_STATE.containing_type = _DRILLINGMACHINESTATUS;
_DRILLINGMACHINECOMMAND.fields_by_name['command'].enum_type = _DRILLINGMACHINECOMMAND_COMMAND
_DRILLINGMACHINECOMMAND_COMPTYPE.containing_type = _DRILLINGMACHINECOMMAND;
_DRILLINGMACHINECOMMAND_COMMAND.containing_type = _DRILLINGMACHINECOMMAND;
DESCRIPTOR.message_types_by_name['DrillingMachineStatus'] = _DRILLINGMACHINESTATUS
DESCRIPTOR.message_types_by_name['DrillingMachineCommand'] = _DRILLINGMACHINECOMMAND

class DrillingMachineStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRILLINGMACHINESTATUS
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.DrillingMachineStatus)

class DrillingMachineCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRILLINGMACHINECOMMAND
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.DrillingMachineCommand)

# @@protoc_insertion_point(module_scope)
