# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ForceFittingMachine.proto',
  package='rockin_msgs',
  serialized_pb='\n\x19\x46orceFittingMachine.proto\x12\x0brockin_msgs\"\xd2\x01\n\x19\x46orceFittingMachineStatus\x12;\n\x05state\x18\x01 \x02(\x0e\x32,.rockin_msgs.ForceFittingMachineStatus.State\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xb2\x02\"O\n\x05State\x12\n\n\x06\x41T_TOP\x10\x00\x12\r\n\tAT_BOTTOM\x10\x01\x12\r\n\tMOVING_UP\x10\x02\x12\x0f\n\x0bMOVING_DOWN\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\"\xae\x01\n\x1a\x46orceFittingMachineCommand\x12@\n\x07\x63ommand\x18\x01 \x02(\x0e\x32/.rockin_msgs.ForceFittingMachineCommand.Command\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xb3\x02\"%\n\x07\x43ommand\x12\r\n\tMOVE_DOWN\x10\x00\x12\x0b\n\x07MOVE_UP\x10\x01\x42\x33\n\x16org.rockin.common_msgsB\x19\x46orceFittingMachineProtos')



_FORCEFITTINGMACHINESTATUS_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.ForceFittingMachineStatus.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=306,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=133,
  serialized_end=172,
)

_FORCEFITTINGMACHINESTATUS_STATE = descriptor.EnumDescriptor(
  name='State',
  full_name='rockin_msgs.ForceFittingMachineStatus.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AT_TOP', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AT_BOTTOM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVING_UP', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVING_DOWN', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=174,
  serialized_end=253,
)

_FORCEFITTINGMACHINECOMMAND_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.ForceFittingMachineCommand.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=307,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=352,
  serialized_end=391,
)

_FORCEFITTINGMACHINECOMMAND_COMMAND = descriptor.EnumDescriptor(
  name='Command',
  full_name='rockin_msgs.ForceFittingMachineCommand.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MOVE_DOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MOVE_UP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=393,
  serialized_end=430,
)


_FORCEFITTINGMACHINESTATUS = descriptor.Descriptor(
  name='ForceFittingMachineStatus',
  full_name='rockin_msgs.ForceFittingMachineStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='state', full_name='rockin_msgs.ForceFittingMachineStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FORCEFITTINGMACHINESTATUS_COMPTYPE,
    _FORCEFITTINGMACHINESTATUS_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=253,
)


_FORCEFITTINGMACHINECOMMAND = descriptor.Descriptor(
  name='ForceFittingMachineCommand',
  full_name='rockin_msgs.ForceFittingMachineCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='rockin_msgs.ForceFittingMachineCommand.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FORCEFITTINGMACHINECOMMAND_COMPTYPE,
    _FORCEFITTINGMACHINECOMMAND_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=430,
)

_FORCEFITTINGMACHINESTATUS.fields_by_name['state'].enum_type = _FORCEFITTINGMACHINESTATUS_STATE
_FORCEFITTINGMACHINESTATUS_COMPTYPE.containing_type = _FORCEFITTINGMACHINESTATUS;
_FORCEFITTINGMACHINESTATUS_STATE.containing_type = _FORCEFITTINGMACHINESTATUS;
_FORCEFITTINGMACHINECOMMAND.fields_by_name['command'].enum_type = _FORCEFITTINGMACHINECOMMAND_COMMAND
_FORCEFITTINGMACHINECOMMAND_COMPTYPE.containing_type = _FORCEFITTINGMACHINECOMMAND;
_FORCEFITTINGMACHINECOMMAND_COMMAND.containing_type = _FORCEFITTINGMACHINECOMMAND;
DESCRIPTOR.message_types_by_name['ForceFittingMachineStatus'] = _FORCEFITTINGMACHINESTATUS
DESCRIPTOR.message_types_by_name['ForceFittingMachineCommand'] = _FORCEFITTINGMACHINECOMMAND

class ForceFittingMachineStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORCEFITTINGMACHINESTATUS
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.ForceFittingMachineStatus)

class ForceFittingMachineCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORCEFITTINGMACHINECOMMAND
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.ForceFittingMachineCommand)

# @@protoc_insertion_point(module_scope)
