# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='LoggingStatus.proto',
  package='rockin_msgs',
  serialized_pb='\n\x13LoggingStatus.proto\x12\x0brockin_msgs\"K\n\rLoggingStatus\x12\x12\n\nis_logging\x18\x01 \x02(\x08\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10oB-\n\x16org.rockin.common_msgsB\x13LoggingStatusProtos')



_LOGGINGSTATUS_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.LoggingStatus.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=111,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=73,
  serialized_end=111,
)


_LOGGINGSTATUS = descriptor.Descriptor(
  name='LoggingStatus',
  full_name='rockin_msgs.LoggingStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='is_logging', full_name='rockin_msgs.LoggingStatus.is_logging', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGGINGSTATUS_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=111,
)

_LOGGINGSTATUS_COMPTYPE.containing_type = _LOGGINGSTATUS;
DESCRIPTOR.message_types_by_name['LoggingStatus'] = _LOGGINGSTATUS

class LoggingStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGGINGSTATUS
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.LoggingStatus)

# @@protoc_insertion_point(module_scope)
