# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Position3D_pb2
import Quaternion_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='Pose3D.proto',
  package='rockin_msgs',
  serialized_pb='\n\x0cPose3D.proto\x12\x0brockin_msgs\x1a\x10Position3D.proto\x1a\x10Quaternion.proto\"a\n\x06Pose3D\x12)\n\x08position\x18\x01 \x02(\x0b\x32\x17.rockin_msgs.Position3D\x12,\n\x0borientation\x18\x02 \x02(\x0b\x32\x17.rockin_msgs.QuaternionB&\n\x16org.rockin.common_msgsB\x0cPose3DProtos')




_POSE3D = descriptor.Descriptor(
  name='Pose3D',
  full_name='rockin_msgs.Pose3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='position', full_name='rockin_msgs.Pose3D.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orientation', full_name='rockin_msgs.Pose3D.orientation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=162,
)

_POSE3D.fields_by_name['position'].message_type = Position3D_pb2._POSITION3D
_POSE3D.fields_by_name['orientation'].message_type = Quaternion_pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Pose3D'] = _POSE3D

class Pose3D(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSE3D
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.Pose3D)

# @@protoc_insertion_point(module_scope)
