# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='RobotStatusReport.proto',
  package='rockin_msgs',
  serialized_pb='\n\x17RobotStatusReport.proto\x12\x0brockin_msgs\"\xe3\x01\n\x0bRobotStatus\x12\x37\n\ncapability\x18\x01 \x01(\x0e\x32#.rockin_msgs.RobotStatus.Capability\x12\x15\n\rfunctionality\x18\x02 \x01(\t\x12\x11\n\tmeta_data\x18\x03 \x01(\t\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xd9\x04\"H\n\nCapability\x12\x0e\n\nNAVIGATION\x10\x00\x12\x10\n\x0cMANIPULATION\x10\x01\x12\x0e\n\nPERCEPTION\x10\x02\x12\x08\n\x04TASK\x10\x03\"f\n\x11RobotStatusReport\x12(\n\x06status\x18\x01 \x03(\x0b\x32\x18.rockin_msgs.RobotStatus\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xda\x04\x42\x31\n\x16org.rockin.common_msgsB\x17RobotStatusReportProtos')



_ROBOTSTATUS_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.RobotStatus.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=601,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=194,
)

_ROBOTSTATUS_CAPABILITY = descriptor.EnumDescriptor(
  name='Capability',
  full_name='rockin_msgs.RobotStatus.Capability',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='NAVIGATION', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MANIPULATION', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PERCEPTION', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=196,
  serialized_end=268,
)

_ROBOTSTATUSREPORT_COMPTYPE = descriptor.EnumDescriptor(
  name='CompType',
  full_name='rockin_msgs.RobotStatusReport.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=602,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=333,
  serialized_end=372,
)


_ROBOTSTATUS = descriptor.Descriptor(
  name='RobotStatus',
  full_name='rockin_msgs.RobotStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='capability', full_name='rockin_msgs.RobotStatus.capability', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='functionality', full_name='rockin_msgs.RobotStatus.functionality', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meta_data', full_name='rockin_msgs.RobotStatus.meta_data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTSTATUS_COMPTYPE,
    _ROBOTSTATUS_CAPABILITY,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=268,
)


_ROBOTSTATUSREPORT = descriptor.Descriptor(
  name='RobotStatusReport',
  full_name='rockin_msgs.RobotStatusReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='rockin_msgs.RobotStatusReport.status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTSTATUSREPORT_COMPTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=270,
  serialized_end=372,
)

_ROBOTSTATUS.fields_by_name['capability'].enum_type = _ROBOTSTATUS_CAPABILITY
_ROBOTSTATUS_COMPTYPE.containing_type = _ROBOTSTATUS;
_ROBOTSTATUS_CAPABILITY.containing_type = _ROBOTSTATUS;
_ROBOTSTATUSREPORT.fields_by_name['status'].message_type = _ROBOTSTATUS
_ROBOTSTATUSREPORT_COMPTYPE.containing_type = _ROBOTSTATUSREPORT;
DESCRIPTOR.message_types_by_name['RobotStatus'] = _ROBOTSTATUS
DESCRIPTOR.message_types_by_name['RobotStatusReport'] = _ROBOTSTATUSREPORT

class RobotStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOTSTATUS
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.RobotStatus)

class RobotStatusReport(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOTSTATUSREPORT
  
  # @@protoc_insertion_point(class_scope:rockin_msgs.RobotStatusReport)

# @@protoc_insertion_point(module_scope)
